name: test

on:
      push:
            branches:
                  - master
      pull_request:
            branches:
                  - master

jobs:
      build:
            runs-on: ubuntu-18.04

            steps:
                  - name: Set up MySQL 5.7
                    uses: mirromutth/mysql-action@master
                    with:
                          mysql version: 5.7
                          mysql database: test
                          mysql root password: ${{ secrets.DatabasePassword }}